/* eslint-disable import/no-anonymous-default-export */
export default {
  logo: "/assets/svg/logo.svg",
  google_logo: "/assets/svg/google.svg",
  ai: "/assets/svg/ai.svg",
  avatar: "/assets/images/avatar.png",
  taskCircle: "/assets/images/taskCircle.png",

  icons: {
    dashboard: "/assets/svg/dashboard.svg",
    task: "/assets/svg/task.svg",
    transcripts: "/assets/svg/transcripts.svg",
    chat: "/assets/svg/chat.svg",
    documents: "/assets/svg/documents.svg",
    settings: "/assets/svg/settings.svg",
    info: "/assets/svg/info.svg",
    spline: "/assets/svg/spline.svg",
    file: "/assets/svg/file.svg",
    sort: "/assets/svg/sort.svg",
    undo: "/assets/svg/undo.svg",
    redo: "/assets/svg/redo.svg",
    underline: "/assets/svg/underline.svg",
    strikethrough: "/assets/svg/strikethrough.svg",
    orderedList: "/assets/svg/ordered-list.svg",
    unorderedList: "/assets/svg/unordered-list.svg",
    alignLeft: "/assets/svg/align-left.svg",
    link: "/assets/svg/link.svg",
    emojiDoc: "/assets/svg/emoji-doc.svg",
    column: "/assets/svg/column.svg",
    triangle: "/assets/svg/triangle.svg",
    plus: "/assets/svg/plus.svg",
    taskCircle: "/assets/svg/taskCircle.svg",
    tableSort: "/assets/svg/tableSort.svg",
    arrowUp: "/assets/svg/arrowUp.svg",
    searchIcon: "/assets/svg/searchIcon.svg",
    clock: "/assets/svg/clock.svg",
    emoji: "/assets/svg/emoji.svg",
    clip: "/assets/svg/clip.svg",
    coachAi: "/assets/svg/coachAi.svg",
    send: "/assets/svg/send.svg",
    chatEmoji: "/assets/svg/chatEmoji.svg"
  }
};
